server:
  port: 8080 #Tomcat端口
spring:
  dubbo:
    application:
      name: springboot-dubbo-demo #应用名
    registry:
      address: zookeeper://47.244.127.184 #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.xgcd.dubbo.impl #扫描的包名
